# Generated by Django 4.1.3 on 2022-12-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receita_categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('tipoReceita', models.CharField(choices=[('1', 'mensal'), ('2', 'eventual')], max_length=1)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita_categoria.categoriareceita')),
            ],
        ),
    ]
