# Generated by Django 4.1.3 on 2022-12-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
